### ISSUE TITLE
文章列表摘要样式问题和代码展示问题

### ISSUE THREAD

**Issue by panjf2000** [zoujiayu/tale-theme-Kratos#1]
![image](https://user-images.githubusercontent.com/7496278/38777526-118cb6a4-40dc-11e8-8f67-3591db06d8aa.png)

文章列表摘要展示提取摘要似乎有时候过多导致样式错乱

还有文章里面的代码样式好像也有点问题，不友好：
![image](https://user-images.githubusercontent.com/7496278/38777519-dff25e50-40db-11e8-9d80-d330d5328680.png)

**Comment by zoujiayu** [comment]
文章摘要问题:默认输出200字，
进入Kratos文件夹找到index.html，编辑index.html，找到${excerpt(200)}修改为${excerpt(80)}即可

代码样式

感谢你的提交，这两天修复下。
